name: "Publish package on NPM"

on:
  release:
    types: [published]

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          # registry-url: "https://npm.pkg.github.com/"
          registry-url: 'https://registry.npmjs.org'
          scope: "@${{ github.repository_owner }}"

      - name: Update package version
        run: npm version ${GITHUB_REF#refs/tags/} --no-git-tag-version

      - name: Publish
        env:
          # NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        # run: npm publish
        run: npm publish --provenance --access public