name: "Publish package on NPM"

on:
  release:
    types: [published]

jobs:
  use-reusable-workflow:
    permissions:
      contents: read
      id-token: write
    uses: theoverengineering/github-workflows/.github/workflows/publish-package.yml@main
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
